import './globals.css'
import { Inter, Montserrat } from 'next/font/google'
import HeaderDesktopOld from "@/components/HeaderDesktopOld";
import Footer from "@/components/Footer";
import HeaderRoot from "@/components/HeaderRoot";

const inter = Inter({ subsets: ['latin'] })
const montserrat = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={"scroll-smooth md:scroll-pt-[2.5rem]"}>
      <body className={inter.className}>
      <HeaderRoot/>
      {children}
      <Footer/>
      </body>
    </html>
  )
}
