import './globals.css'
import { Inter, Montserrat } from 'next/font/google'
import HeaderDesktop from "@/components/HeaderDesktop";
import Footer from "@/components/Footer";
import HeaderRoot from "@/components/HeaderRoot";

const inter = Inter({ subsets: ['latin'] })
const montserrat = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <HeaderRoot/>
      {children}
      <Footer/>
      </body>
    </html>
  )
}
